#!/usr/bin/env sh

touch /data/logs/access.log
touch /data/logs/error.log
touch /data/logs/application.log
chgrp www-data /data/logs/*
chmod 775 /data/logs/*

exec tail -qF /data/logs/access.log /data/logs/error.log /data/logs/application.log